server:
  port: 9090

spring:
  application:
    name: basic
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:subscription_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    initialization-mode: always
    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      minimum-idle: 1
      maximum-pool-size: 10
