server:
  port: 9090

spring:
  application:
    name: basic
  liquibase:
    contexts: default
    change-log: classpath:/db/changelog/main.xml
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fac_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    initialization-mode: always
    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      minimum-idle: 1
      maximum-pool-size: 10
